### ISSUE TITLE
执行train.py报KeyError: 0错误

### ISSUE THREAD

**Issue by zhufeizzz** [tangqiaoyu/ToolAlpaca#20]
train.py这段代码正确吗？这个脚本的数据集入参是train_data.json吗？如果source是train_data.json中的一条数据，这里明显解析不出来啊。我主要是想看下处理后的微调数据格式是什么样的。
```
def preprocess(
    sources,
    tokenizer: transformers.PreTrainedTokenizer,
) -> Dict:

    # Apply prompt templates
    conversations = []
    trainables = []
    for i, source in enumerate(sources):
        source[0][-1] += " " + EOS_TOKEN
        conversations.append(source[0])
        trainables.append(source[1])
```

报错信息
```
Loading data...
Formatting inputs...
Traceback (most recent call last):
  File "/content/ToolAlpaca/train.py", line 212, in <module>
    train()
  File "/content/ToolAlpaca/train.py", line 207, in train
    data_module = make_supervised_data_module(tokenizer=tokenizer,
  File "/content/ToolAlpaca/train.py", line 181, in make_supervised_data_module
    train_dataset = dataset_cls(tokenizer=tokenizer,
  File "/content/ToolAlpaca/train.py", line 127, in __init__
    data_dict = preprocess(list_data_dict, tokenizer)
  File "/content/ToolAlpaca/train.py", line 78, in preprocess
    source[0][-1] += " " + EOS_TOKEN
KeyError: 0
```

**Comment by tangqiaoyu** [comment]
需要先调用 `build_dataset.py`

**Comment by zhufeizzz** [comment]
> 需要先调用 `build_dataset.py`

这些过程数据文件能否也提交一下，办公网络环境有些命令不方便执行。其它的文件还有/data/api_data.json

**Comment by tangqiaoyu** [comment]
`build_dataset.py`不需要什么网络要求，可以直接执行的。
`data/public_apis.json`我已经上传了，可以自行下载一下。
